from django.db import models


class Patient(models.Model):
    ID = models.CharField(max_length=254, null = True)
    name = models.CharField(max_length=254, null = True)

class PatientImmutableCharacters(models.Model):
    ID_0_0 = models.CharField(max_length=254, null = True)
    Vozrast_3_0 = models.FloatField(null=True, blank=True)
    Pol_1_1 = models.CharField(max_length=254, null = True)
    Etnos_3_1 = models.CharField(max_length=254, null = True)
    Nacionalnost_4_1 = models.CharField(max_length=254, null = True)
    CHislo_bratev_sester_60_2 = models.CharField(max_length=254, null = True)
    Diabet_otec_61_2 = models.CharField(max_length=254, null = True)
    Diabet_mat_62_2 = models.CharField(max_length=254, null = True)
    Diabet_bratya_sestry_63_2 = models.CharField(max_length=254, null = True)
    Diabet_bratev_sester_64_2 = models.CharField(max_length=254, null = True)
    IBS_otec_65_2 = models.CharField(max_length=254, null = True)
    IBS_mat_66_2 = models.CharField(max_length=254, null = True)
    IBS_bratya_sestry_67_2 = models.CharField(max_length=254, null = True)
    IBS_bratev_sester_68_2 = models.CharField(max_length=254, null = True)
    AG_otec_69_2 = models.CharField(max_length=254, null = True)
    AG_mat_70_2 = models.CharField(max_length=254, null = True)
    AG_bratya_sestry_71_2 = models.CharField(max_length=254, null = True)
    AG_bratev_sester_72_2 = models.CharField(max_length=254, null = True)
    Insult_otec_73_2 = models.CharField(max_length=254, null = True)
    Insult_mat_74_2 = models.CharField(max_length=254, null = True)
    Insult_bratya_sestry_75_2 = models.CharField(max_length=254, null = True)
    Insult_bratev_sester_76_2 = models.CharField(max_length=254, null = True)
    Rak_otec_77_2 = models.CharField(max_length=254, null = True)
    Rak_otec_uchastok_78_2 = models.CharField(max_length=254, null = True)
    Rak_mat_79_2 = models.CharField(max_length=254, null = True)
    Rak_mat_uchastok_80_2 = models.CharField(max_length=254, null = True)
    Rak_bratya_sestry_81_2 = models.CharField(max_length=254, null = True)
    Rak_bratev_sester_82_2 = models.CharField(max_length=254, null = True)
    Rak_bratya_sestry_uchastok_83_2 = models.CharField(max_length=254, null = True)

class PatientCharacters(models.Model):
    ID_0_0 = models.CharField(max_length=254, null = True)
    Mesto_prozhivaniya_1gorod_2selo_1_0 = models.FloatField(null=True, blank=True)
    Data_rozhdeniya_2_0 = models.CharField(max_length=254, null = True)
    ID_0_1 = models.CharField(max_length=254, null = True)
    Semya_2_1 = models.CharField(max_length=254, null = True)
    Religiya_5_1 = models.CharField(max_length=254, null = True)
    Obrazovanie_6_1 = models.CharField(max_length=254, null = True)
    Professiya_7_1 = models.CharField(max_length=254, null = True)
    Vy_rabotaete_8_1 = models.FloatField(null=True, blank=True)
    Vyhod_na_pensiu_9_1 = models.FloatField(null=True, blank=True)
    Prekraschenie_raboty_po_bolezni_10_1 = models.FloatField(null=True, blank=True)
    Saharnyi_diabet_11_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_saharnogo_diabeta_12_1 = models.CharField(max_length=254, null = True)
    Arterialnaya_gipertenziya_13_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_arterialnoi_gipertenzii_14_1 = models.FloatField(null=True, blank=True)
    ONMK_15_1 = models.FloatField(null=True, blank=True)
    Danost_ONMK_16_1 = models.CharField(max_length=254, null = True)
    Stenokardiya_IBS_infarkt_miokarda_17_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_stenokardii_IBS_infarkta_miokarda_18_1 = models.FloatField(null=True, blank=True)
    Serdechnaya_nedostatochnost_19_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_serdechnoi_nedostatochnosti_20_1 = models.CharField(max_length=254, null = True)
    Prochie_zabolevaniya_serdca_21_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_prochih_zabolevanii_serdca_22_1 = models.CharField(max_length=254, null = True)
    Gepetit_23_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_gepatita_24_1 = models.CharField(max_length=254, null = True)
    Onkologiya_25_1 = models.FloatField(null=True, blank=True)
    Onkologiya_lokya_26_1 = models.CharField(max_length=254, null = True)
    Dlitelnost_onkologicheskogo_processa_27_1 = models.CharField(max_length=254, null = True)
    Hronicheskoe_zabolevanie_legkih_28_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_hron_zabolevaniya_legkih_29_1 = models.CharField(max_length=254, null = True)
    Bronzhialnaya_astma_30_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_bronhialnoi_astmy_31_1 = models.CharField(max_length=254, null = True)
    Tuberkulez_legkih_32_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_tuberkuleza_legkih_33_1 = models.CharField(max_length=254, null = True)
    VICHSPID_34_1 = models.FloatField(null=True, blank=True)
    Dlitelnost_VICHSPID_35_1 = models.CharField(max_length=254, null = True)
    Regulyarnyi_prim_lekarstvennyh_sredstv_36_1 = models.FloatField(null=True, blank=True)
    Lekarstvo_davlenie_37_1 = models.FloatField(null=True, blank=True)
    Lekarstvo_holesterin_38_1 = models.FloatField(null=True, blank=True)
    Lekarstvo_insult_39_1 = models.FloatField(null=True, blank=True)
    Lekarstvo_diabet_40_1 = models.FloatField(null=True, blank=True)
    Lekarstvo_astma_41_1 = models.FloatField(null=True, blank=True)
    Lekarstvo_Kitai_42_1 = models.FloatField(null=True, blank=True)
    Lekarstvo_prochie_43_1 = models.FloatField(null=True, blank=True)
    Lekarstvo_prochie_utochnenie_44_1 = models.CharField(max_length=254, null = True)
    Lekarstvo_neizvestno_45_1 = models.FloatField(null=True, blank=True)
    Perechen_lekarstva_46_1 = models.CharField(max_length=254, null = True)
    Travmy_za_god_47_1 = models.FloatField(null=True, blank=True)
    Perelomy_48_1 = models.FloatField(null=True, blank=True)
    CHislo_perelom_49_1 = models.CharField(max_length=254, null = True)
    Let_proshlo_50_1 = models.CharField(max_length=254, null = True)
    Status_Kureniya_51_1 = models.CharField(max_length=254, null = True)
    Vozrast_kureniya_52_1 = models.CharField(max_length=254, null = True)
    Sigaret_v_den_53_1 = models.CharField(max_length=254, null = True)
    Sigaret_let_54_1 = models.CharField(max_length=254, null = True)
    Sigaret_prekr_let_55_1 = models.CharField(max_length=254, null = True)
    Sigaret_prekr_mes_56_1 = models.CharField(max_length=254, null = True)
    Passivnoe_kurenie_57_1 = models.FloatField(null=True, blank=True)
    CHastota_pass_kur_58_1 = models.CharField(max_length=254, null = True)
    Alkogol_59_1 = models.CharField(max_length=254, null = True)
    Vozrast_alkog_60_1 = models.CharField(max_length=254, null = True)
    Vodka_razmer_61_1 = models.CharField(max_length=254, null = True)
    Vodka_regulyar_62_1 = models.CharField(max_length=254, null = True)
    Vodka_porcii_63_1 = models.CharField(max_length=254, null = True)
    Vodka_let_64_1 = models.CharField(max_length=254, null = True)
    Vodka_otkaz_let_65_1 = models.CharField(max_length=254, null = True)
    Vino_regulyar_66_1 = models.CharField(max_length=254, null = True)
    Vino_porcii_67_1 = models.CharField(max_length=254, null = True)
    Vino_let_68_1 = models.CharField(max_length=254, null = True)
    Vino_otkaz_let_69_1 = models.CharField(max_length=254, null = True)
    Pivo_razmer_70_1 = models.CharField(max_length=254, null = True)
    Pivo_regulyar_71_1 = models.CharField(max_length=254, null = True)
    Pivo_porcii_72_1 = models.CharField(max_length=254, null = True)
    Pivo_let_73_1 = models.CharField(max_length=254, null = True)
    Pivo_otkaz_let_74_1 = models.CharField(max_length=254, null = True)
    Samogon_razmer_75_1 = models.CharField(max_length=254, null = True)
    Samogon_regulyar_76_1 = models.CharField(max_length=254, null = True)
    Samogon_porcii_77_1 = models.CharField(max_length=254, null = True)
    Samogon_let_78_1 = models.CharField(max_length=254, null = True)
    Samogon_otkaz_let_79_1 = models.CharField(max_length=254, null = True)
    Kr_vino_regulyar_80_1 = models.CharField(max_length=254, null = True)
    Kr_vino_porcii_81_1 = models.CharField(max_length=254, null = True)
    Kr_vino_let_82_1 = models.CharField(max_length=254, null = True)
    Kr_vino_otkaz_let_83_1 = models.CharField(max_length=254, null = True)
    porcii_v_den5_84_1 = models.FloatField(null=True, blank=True)
    porcii_dnei_v_mes5_85_1 = models.CharField(max_length=254, null = True)
    porcii_chislo_porcii5_86_1 = models.CharField(max_length=254, null = True)
    Vremya_zasypaniya_87_1 = models.CharField(max_length=254, null = True)
    Vremya_probuzhdeniya_88_1 = models.CharField(max_length=254, null = True)
    Son_posle_obeda_89_1 = models.FloatField(null=True, blank=True)
    Sonchas_min_90_1 = models.CharField(max_length=254, null = True)
    Sport_kluby_91_1 = models.FloatField(null=True, blank=True)
    Sport_chastota_v_mes_92_1 = models.CharField(max_length=254, null = True)
    Sport_chastota_v_god_93_1 = models.CharField(max_length=254, null = True)
    Religiya_kluby_94_1 = models.FloatField(null=True, blank=True)
    Religiya_chastota_v_mes_95_1 = models.CharField(max_length=254, null = True)
    Religiya_chastota_v_god_96_1 = models.CharField(max_length=254, null = True)
    Prochee_kluby_97_1 = models.FloatField(null=True, blank=True)
    Konkretno_98_1 = models.CharField(max_length=254, null = True)
    Prochee_chastota_v_mes_99_1 = models.CharField(max_length=254, null = True)
    Prochee_chastota_v_god_100_1 = models.CharField(max_length=254, null = True)
    Ludi_obychno_chestnye_1_2 = models.CharField(max_length=254, null = True)
    Esli_ya_delau_2_2 = models.CharField(max_length=254, null = True)
    Reklama_maslo_3_2 = models.CharField(max_length=254, null = True)
    Reklama_muka_4_2 = models.CharField(max_length=254, null = True)
    Reklama_ris_5_2 = models.CharField(max_length=254, null = True)
    Reklama_bezalkogol_6_2 = models.CharField(max_length=254, null = True)
    Reklama_sneki_7_2 = models.CharField(max_length=254, null = True)
    Reklama_sigarety_8_2 = models.CharField(max_length=254, null = True)
    Reklama_alkogol_9_2 = models.CharField(max_length=254, null = True)
    Pomosch_obsch_organ_10_2 = models.CharField(max_length=254, null = True)
    Pomosch_OO_kolvo_11_2 = models.CharField(max_length=254, null = True)
    Pomosch_relig_organ_12_2 = models.CharField(max_length=254, null = True)
    Pomosch_RO_kolvo_13_2 = models.CharField(max_length=254, null = True)
    Pomosch_semya_kolvo_14_2 = models.CharField(max_length=254, null = True)
    Pomosch_prochee_15_2 = models.CharField(max_length=254, null = True)
    Pomosch_prochee_kolvo_16_2 = models.CharField(max_length=254, null = True)
    Poterya_raboty36_17_2 = models.FloatField(null=True, blank=True)
    Vyhod_na_pensiu36_18_2 = models.FloatField(null=True, blank=True)
    Bankrotstvo36_19_2 = models.FloatField(null=True, blank=True)
    Grabezh36_20_2 = models.FloatField(null=True, blank=True)
    Razvod36_21_2 = models.FloatField(null=True, blank=True)
    Konflikt_v_seme36_22_2 = models.FloatField(null=True, blank=True)
    Konfl_utochnit36_23_2 = models.CharField(max_length=254, null = True)
    Bolezn36_24_2 = models.FloatField(null=True, blank=True)
    Nasilie36_25_2 = models.FloatField(null=True, blank=True)
    Voina36_26_2 = models.FloatField(null=True, blank=True)
    Smert_suprugai36_27_2 = models.FloatField(null=True, blank=True)
    Smert_chlsemi36_28_2 = models.FloatField(null=True, blank=True)
    Inoi_stress36_29_2 = models.FloatField(null=True, blank=True)
    Stress_utochnit36_30_2 = models.CharField(max_length=254, null = True)
    Svadba36_31_2 = models.FloatField(null=True, blank=True)
    Novaya_rabota36_32_2 = models.FloatField(null=True, blank=True)
    Rozhd_rebenka36_33_2 = models.FloatField(null=True, blank=True)
    Otdelenie_ot_semi36_34_2 = models.FloatField(null=True, blank=True)
    Otsustv_produktov36_35_2 = models.FloatField(null=True, blank=True)
    Stress_na_rabote_36_2 = models.CharField(max_length=254, null = True)
    Stress_doma_37_2 = models.CharField(max_length=254, null = True)
    Stress_izza_finans_38_2 = models.CharField(max_length=254, null = True)
    Depressiya_39_2 = models.FloatField(null=True, blank=True)
    Depressiya_a_40_2 = models.FloatField(null=True, blank=True)
    Depressiya_b_41_2 = models.FloatField(null=True, blank=True)
    Depressiya_c_42_2 = models.FloatField(null=True, blank=True)
    Depressiya_d_43_2 = models.FloatField(null=True, blank=True)
    Depressiya_e_44_2 = models.FloatField(null=True, blank=True)
    Depressiya_f_45_2 = models.FloatField(null=True, blank=True)
    Depressiya_g_46_2 = models.FloatField(null=True, blank=True)
    vershat_obychnye_pokupki_v_magazine_v_shagovoi_dostupnosti_47_2 = models.CharField(max_length=254, null = True)
    _zatrudneno_iz_za_skorostnogo_rezhima_i_ili_kol_transporta_48_2 = models.CharField(max_length=254, null = True)
    et_musora_zagryazneniya_vozduha_chrezmernogo_urovnya_shuma_49_2 = models.CharField(max_length=254, null = True)
    Ulicy_v_okrestnostyah_v_nochnoe_vremya_horosho_osvescheny_50_2 = models.CharField(max_length=254, null = True)
    ya_vstrechau_dr_ludei_vo_vremya_proguloi_po_okrestnostyah_51_2 = models.CharField(max_length=254, null = True)
    bschatsya_s_drugimi_ludmi_vo_vremya_progulki_po_okresnosti_52_2 = models.CharField(max_length=254, null = True)
    vysokii_uroven_prestupnosti_v_okrestnostyah_53_2 = models.CharField(max_length=254, null = True)
    problema_s_bezdomnymi_sobakami_v_okrestnostyah_54_2 = models.CharField(max_length=254, null = True)
    Rasstoyanie_Minut_do_magazina_55_2 = models.FloatField(null=True, blank=True)
    Rasstoyanie_Minut_do_banka_56_2 = models.FloatField(null=True, blank=True)
    Rasstoyanie_Minut_do_pochty_57_2 = models.FloatField(null=True, blank=True)
    Rasstoyanie_Minut_do_restorana_58_2 = models.CharField(max_length=254, null = True)
    Rasstoyanie_Minut_do_kafe_59_2 = models.CharField(max_length=254, null = True)
    SAD1_1_3 = models.FloatField(null=True, blank=True)
    DAD1_2_3 = models.FloatField(null=True, blank=True)
    SAD2_3_3 = models.FloatField(null=True, blank=True)
    DAD2_4_3 = models.FloatField(null=True, blank=True)
    CHSS1_5_3 = models.FloatField(null=True, blank=True)
    CHSS2_6_3 = models.FloatField(null=True, blank=True)
    OT1_7_3 = models.FloatField(null=True, blank=True)
    OT2_8_3 = models.FloatField(null=True, blank=True)
    OB1_9_3 = models.FloatField(null=True, blank=True)
    OB2_10_3 = models.FloatField(null=True, blank=True)
    Ves_11_3 = models.FloatField(null=True, blank=True)
    Rost_12_3 = models.FloatField(null=True, blank=True)
    Plecho_13_3 = models.FloatField(null=True, blank=True)
    Golen_14_3 = models.FloatField(null=True, blank=True)
    Golova_15_3 = models.FloatField(null=True, blank=True)
    Sila_levaya1_16_3 = models.FloatField(null=True, blank=True)
    Sila_levaya2_17_3 = models.FloatField(null=True, blank=True)
    Sila_levaya3_18_3 = models.FloatField(null=True, blank=True)
    Sila_pravaya1_19_3 = models.FloatField(null=True, blank=True)
    Sila_pravaya2_20_3 = models.FloatField(null=True, blank=True)
    Sila_pravaya3_21_3 = models.FloatField(null=True, blank=True)
    FEV1_22_3 = models.FloatField(null=True, blank=True)
    FEV1_23_3 = models.FloatField(null=True, blank=True)
    FVC_24_3 = models.FloatField(null=True, blank=True)
    FVC_25_3 = models.FloatField(null=True, blank=True)
    PEFR_26_3 = models.FloatField(null=True, blank=True)
    PEFR_27_3 = models.FloatField(null=True, blank=True)
    Glukoza_28_3 = models.FloatField(null=True, blank=True)
    Holesterin_29_3 = models.FloatField(null=True, blank=True)
    Trigliceridy_30_3 = models.FloatField(null=True, blank=True)
    LPVP_31_3 = models.FloatField(null=True, blank=True)
    LPNP_32_3 = models.FloatField(null=True, blank=True)
    Natrii_33_3 = models.FloatField(null=True, blank=True)
    Kalii_34_3 = models.FloatField(null=True, blank=True)
    Kreatinin_35_3 = models.FloatField(null=True, blank=True)
    Polnyi_ves_tela_36_3 = models.FloatField(null=True, blank=True)
    zhira_37_3 = models.FloatField(null=True, blank=True)
    vody_38_3 = models.FloatField(null=True, blank=True)
    Myshechnaya_massa_39_3 = models.FloatField(null=True, blank=True)
    Fiz_sostoyanie_40_3 = models.FloatField(null=True, blank=True)
    BMR_41_3 = models.FloatField(null=True, blank=True)
    Metab_vozrast_42_3 = models.FloatField(null=True, blank=True)
    Kost_massa_43_3 = models.FloatField(null=True, blank=True)
    Dolya_vnutr_zhira_44_3 = models.FloatField(null=True, blank=True)
    EKG_norma_45_3 = models.FloatField(null=True, blank=True)
    Pat_zub_Q_peredii_46_3 = models.FloatField(null=True, blank=True)
    Pat_zub_Q_nizhnii_47_3 = models.FloatField(null=True, blank=True)
    Pat_zub_Q_lateralnyi_48_3 = models.FloatField(null=True, blank=True)
    Pat_zub_Q_perlat_49_3 = models.FloatField(null=True, blank=True)
    Pat_zub_Q_zadnii_50_3 = models.FloatField(null=True, blank=True)
    Pat_zub_Q_net_51_3 = models.FloatField(null=True, blank=True)
    Elevaciya_ST_perednii_52_3 = models.FloatField(null=True, blank=True)
    Elevaciya_ST_nizhnii_53_3 = models.FloatField(null=True, blank=True)
    Elevaciya_ST_lateralnyi_54_3 = models.FloatField(null=True, blank=True)
    Elevaciya_ST_peredlat_55_3 = models.FloatField(null=True, blank=True)
    Elevaciya_ST_zadnii_56_3 = models.FloatField(null=True, blank=True)
    Elevaciya_ST_net_57_3 = models.FloatField(null=True, blank=True)
    Depressiya_ST_perednii_58_3 = models.FloatField(null=True, blank=True)
    Depressiya_ST_nizhnii_59_3 = models.FloatField(null=True, blank=True)
    Depressiya_ST_lateralnyi_60_3 = models.FloatField(null=True, blank=True)
    Depressiya_ST_peredlat_61_3 = models.FloatField(null=True, blank=True)
    Depressiya_ST_zadnii_62_3 = models.FloatField(null=True, blank=True)
    Depressiya_ST_net_63_3 = models.FloatField(null=True, blank=True)
    Inversiya_T_perednii_64_3 = models.FloatField(null=True, blank=True)
    Inversiya_T_nizhnii_65_3 = models.FloatField(null=True, blank=True)
    Inversiya_T_lateralnyi_66_3 = models.FloatField(null=True, blank=True)
    Inversiya_T_peredlat_67_3 = models.FloatField(null=True, blank=True)
    Inversiya_T_zadnii_68_3 = models.FloatField(null=True, blank=True)
    Inversiya_T_net_69_3 = models.FloatField(null=True, blank=True)
    RS_70_3 = models.FloatField(null=True, blank=True)
    Gipertrofiya_LZH_71_3 = models.FloatField(null=True, blank=True)
    Voltazhnye_kriterii_72_3 = models.FloatField(null=True, blank=True)
    Depr_ST_inver_T_73_3 = models.FloatField(null=True, blank=True)
    Otklonenie_el_osi_74_3 = models.FloatField(null=True, blank=True)
    Narushenie_provodimosti_75_3 = models.FloatField(null=True, blank=True)
    Utochnenie_76_3 = models.CharField(max_length=254, null = True)
    QT_77_3 = models.FloatField(null=True, blank=True)
    Anomalnyi_ritm_78_3 = models.CharField(max_length=254, null = True)
    Drugie_anomalii_79_3 = models.CharField(max_length=254, null = True)
    Kolvo_chel_v_dh_1_4 = models.FloatField(null=True, blank=True)
    Tip_kryshi_1_5 = models.CharField(max_length=254, null = True)
    Elektrvo_2_5 = models.FloatField(null=True, blank=True)
    Tip_topliva_3_5 = models.CharField(max_length=254, null = True)
    Istochnik_tepla_4_5 = models.CharField(max_length=254, null = True)
    Istochnik_vody_5_5 = models.CharField(max_length=254, null = True)
    Vody_net_min_6_5 = models.CharField(max_length=254, null = True)
    Moped_7_5 = models.FloatField(null=True, blank=True)
    Avtomobil_8_5 = models.FloatField(null=True, blank=True)
    CHislo_avto_9_5 = models.FloatField(null=True, blank=True)
    Prochie_avto_10_5 = models.FloatField(null=True, blank=True)
    Velosiped_11_5 = models.FloatField(null=True, blank=True)
    Povozki_12_5 = models.FloatField(null=True, blank=True)
    PK_13_5 = models.FloatField(null=True, blank=True)
    CHislo_PK_14_5 = models.FloatField(null=True, blank=True)
    Stir_mashina_15_5 = models.FloatField(null=True, blank=True)
    Kuh_kombain_16_5 = models.FloatField(null=True, blank=True)
    Holodilnik_17_5 = models.FloatField(null=True, blank=True)
    Televizor_18_5 = models.FloatField(null=True, blank=True)
    CHislo_telev_19_5 = models.FloatField(null=True, blank=True)
    Stereo_20_5 = models.FloatField(null=True, blank=True)
    Telefon_21_5 = models.FloatField(null=True, blank=True)
    Gazonokos_22_5 = models.FloatField(null=True, blank=True)
    Snegouborsch_23_5 = models.FloatField(null=True, blank=True)
    Mikrovolnovka_24_5 = models.FloatField(null=True, blank=True)
    Posudomoech_25_5 = models.FloatField(null=True, blank=True)
    Ezhemes_dohod_26_5 = models.FloatField(null=True, blank=True)
    Dengi_na_pischu_27_5 = models.FloatField(null=True, blank=True)
    Dacha_28_5 = models.FloatField(null=True, blank=True)
    Ploschad_dachi_29_5 = models.CharField(max_length=254, null = True)
    Mesto_dlya_prigot_pischi_30_5 = models.CharField(max_length=254, null = True)
    Vytyazhka_31_5 = models.CharField(max_length=254, null = True)
    Gotovka_vne_doma_mesyac_32_5 = models.FloatField(null=True, blank=True)
    Vopros_10a_mesyac_33_5 = models.CharField(max_length=254, null = True)
    Vopros_10a_5_let_34_5 = models.CharField(max_length=254, null = True)
    Vopros_10b_mesyac_35_5 = models.CharField(max_length=254, null = True)
    Vopros_10b_5_let_36_5 = models.CharField(max_length=254, null = True)
    Vopros_10c_mesyac_37_5 = models.CharField(max_length=254, null = True)
    Vopros_10c_5_let_38_5 = models.CharField(max_length=254, null = True)
    Kvartira_39_5 = models.FloatField(null=True, blank=True)
    Dr_kvartira_40_5 = models.FloatField(null=True, blank=True)
    Holodnaya_dacha_41_5 = models.FloatField(null=True, blank=True)
    Teplaya_dacha_42_5 = models.FloatField(null=True, blank=True)
    Mashina_43_5 = models.FloatField(null=True, blank=True)
    Garazh_44_5 = models.FloatField(null=True, blank=True)
    Ferma_45_5 = models.FloatField(null=True, blank=True)
    Lavka_46_5 = models.FloatField(null=True, blank=True)
    Drugoe_47_5 = models.FloatField(null=True, blank=True)
    Dr_utochnit_48_5 = models.CharField(max_length=254, null = True)
    CHast_dohoda_na_edu_49_5 = models.CharField(max_length=254, null = True)
    CHast_dohoda_na_edu_49_5_50_5 = models.CharField(max_length=254, null = True)
    Dostatok_po_srav_s_drug_51_5 = models.CharField(max_length=254, null = True)
    Tip_zhilya_52_5 = models.CharField(max_length=254, null = True)
    CHislo_komnat_53_5 = models.FloatField(null=True, blank=True)
    Ploschad_zhilya_54_5 = models.FloatField(null=True, blank=True)
    Vremya_bakaleya_1_6 = models.CharField(max_length=254, null = True)
    Vremya_odezhda_2_6 = models.CharField(max_length=254, null = True)
    Vremya_frukty_3_6 = models.CharField(max_length=254, null = True)
    Vremya_restoran_4_6 = models.CharField(max_length=254, null = True)
    Vremya_bank_5_6 = models.CharField(max_length=254, null = True)
    Vremya_videoprokat_6_6 = models.CharField(max_length=254, null = True)
    Vremya_apteka_7_6 = models.CharField(max_length=254, null = True)
    Vremya_do_raboty_8_6 = models.CharField(max_length=254, null = True)
    Vremya_ostanovka_9_6 = models.CharField(max_length=254, null = True)
    Vremya_park_10_6 = models.CharField(max_length=254, null = True)
    Vopros_B1_11_6 = models.CharField(max_length=254, null = True)
    Vopros_B2_12_6 = models.CharField(max_length=254, null = True)
    Vopros_B3_13_6 = models.CharField(max_length=254, null = True)
    Vopros_B4_14_6 = models.CharField(max_length=254, null = True)
    Vopros_C1_15_6 = models.CharField(max_length=254, null = True)
    Vopros_C2_16_6 = models.CharField(max_length=254, null = True)
    Vopros_C3_17_6 = models.CharField(max_length=254, null = True)
    Vopros_D1_18_6 = models.CharField(max_length=254, null = True)
    Vopros_D2_19_6 = models.CharField(max_length=254, null = True)
    Vopros_D3_20_6 = models.CharField(max_length=254, null = True)
    Vopros_E1_21_6 = models.CharField(max_length=254, null = True)
    Vopros_E2_22_6 = models.CharField(max_length=254, null = True)
    Vopros_E3_23_6 = models.CharField(max_length=254, null = True)
    Vopros_F1_24_6 = models.CharField(max_length=254, null = True)
    Vopros_F2_25_6 = models.CharField(max_length=254, null = True)
    Vopros_F3_26_6 = models.CharField(max_length=254, null = True)
    Vopros_G1_27_6 = models.CharField(max_length=254, null = True)
    Vopros_G2_28_6 = models.CharField(max_length=254, null = True)
    Vopros_G3_29_6 = models.CharField(max_length=254, null = True)
    Vopros_Ha_30_6 = models.CharField(max_length=254, null = True)
    Vopros_Hb_31_6 = models.CharField(max_length=254, null = True)
    Vopros_Hc_32_6 = models.CharField(max_length=254, null = True)
    Vopros_Hd_33_6 = models.CharField(max_length=254, null = True)
    Vopros_He_34_6 = models.CharField(max_length=254, null = True)
    Vopros_Hf_35_6 = models.CharField(max_length=254, null = True)
    Vopros_Hg_36_6 = models.CharField(max_length=254, null = True)
    Vopros_Hh_37_6 = models.CharField(max_length=254, null = True)
    Vopros_Hi_38_6 = models.CharField(max_length=254, null = True)
    Vopros_Hj_39_6 = models.CharField(max_length=254, null = True)
    Professiya_1_7 = models.CharField(max_length=254, null = True)
    Rabota_2_7 = models.FloatField(null=True, blank=True)
    Tyazhelyi_trud_na_rabote_dni1_3_7 = models.FloatField(null=True, blank=True)
    Tyazhelyi_trud_na_rabote_chasy1_4_7 = models.CharField(max_length=254, null = True)
    Tyazhelyi_trud_na_rabote_minuty1_5_7 = models.CharField(max_length=254, null = True)
    Srednie_trud_na_rabote_dni1_6_7 = models.FloatField(null=True, blank=True)
    Srednie_trud_na_rabote_chasy1_7_7 = models.CharField(max_length=254, null = True)
    Srednie_trud_na_rabote_minuty1_8_7 = models.CharField(max_length=254, null = True)
    Peshkom_na_rabote_dni1_9_7 = models.FloatField(null=True, blank=True)
    Peshkom_na_rabote_chasy1_10_7 = models.CharField(max_length=254, null = True)
    Peshkom_na_rabote_minuty1_11_7 = models.CharField(max_length=254, null = True)
    Avto_dni2_12_7 = models.FloatField(null=True, blank=True)
    Avto_chasy2_13_7 = models.CharField(max_length=254, null = True)
    Avto_minuty2_14_7 = models.CharField(max_length=254, null = True)
    Velosiped_dni2_15_7 = models.FloatField(null=True, blank=True)
    Velosiped_chasy2_16_7 = models.CharField(max_length=254, null = True)
    Velosiped_minuty2_17_7 = models.CharField(max_length=254, null = True)
    Peshkom_dni2_18_7 = models.FloatField(null=True, blank=True)
    Peshkom_chasy2_19_7 = models.CharField(max_length=254, null = True)
    Peshkom_minuty2_20_7 = models.CharField(max_length=254, null = True)
    Tyazhelyi_trud_sad_dni3_21_7 = models.FloatField(null=True, blank=True)
    Tyazhelyi_trud_sad_chasy3_22_7 = models.CharField(max_length=254, null = True)
    Tyazhelyi_trud_sad_minuty3_23_7 = models.CharField(max_length=254, null = True)
    Srednii_trud_sad_dni3_24_7 = models.FloatField(null=True, blank=True)
    Srednii_trud_sad_chasy3_25_7 = models.CharField(max_length=254, null = True)
    Srednii_trud_sad_minuty3_26_7 = models.CharField(max_length=254, null = True)
    Srednii_trud_doma_dni3_27_7 = models.FloatField(null=True, blank=True)
    Srednii_trud_doma_chasy3_28_7 = models.CharField(max_length=254, null = True)
    Srednii_trud_doma_minuty3_29_7 = models.CharField(max_length=254, null = True)
    Peshkom_dni4_30_7 = models.FloatField(null=True, blank=True)
    Peshkom_chasy4_31_7 = models.CharField(max_length=254, null = True)
    Peshkom_minuty4_32_7 = models.CharField(max_length=254, null = True)
    Sport_tyazhelyi_dni4_33_7 = models.FloatField(null=True, blank=True)
    Sport_tyazhelyi_chasy4_34_7 = models.CharField(max_length=254, null = True)
    Sport_tyazhelyi_minuty4_35_7 = models.CharField(max_length=254, null = True)
    Sport_srednii_dni4_36_7 = models.FloatField(null=True, blank=True)
    Sport_srednii_chasy4_37_7 = models.CharField(max_length=254, null = True)
    Sport_srednii_minuty4_38_7 = models.CharField(max_length=254, null = True)
    Sidya_na_rabote_chas_39_7 = models.CharField(max_length=254, null = True)
    Sidya_na_rabote_min_40_7 = models.FloatField(null=True, blank=True)
    Sidya_v_vyhodnye_chas_41_7 = models.FloatField(null=True, blank=True)
    Sidya_v_vyhodnye_min_42_7 = models.CharField(max_length=254, null = True)
    ID_0_8 = models.CharField(max_length=254, null = True)
    Obschaya_fizaktivnost_METminned_ang_1_8 = models.FloatField(null=True, blank=True)
    Aktivnost_za_nedelu_2_8 = models.FloatField(null=True, blank=True)
    Srznachenieden_3_8 = models.FloatField(null=True, blank=True)
    Sraktivnostden_rabota_4_8 = models.FloatField(null=True, blank=True)
    Sraktivnostden_transport_5_8 = models.FloatField(null=True, blank=True)
    Sraktivnostden_sport_6_8 = models.FloatField(null=True, blank=True)
    rabota_7_8 = models.FloatField(null=True, blank=True)
    transport_8_8 = models.FloatField(null=True, blank=True)
    sport_9_8 = models.FloatField(null=True, blank=True)
    Obschee_vremya_sideniya_v_min_10_8 = models.FloatField(null=True, blank=True)
    Progulka_METminned_11_8 = models.FloatField(null=True, blank=True)
    Umerennyi_METminned_12_8 = models.FloatField(null=True, blank=True)
    Energichnyi_METminned_13_8 = models.FloatField(null=True, blank=True)
    Obschaya_fizaktivnost_METminned_KF_14_8 = models.FloatField(null=True, blank=True)
    ROHodba_METminned_15_8 = models.FloatField(null=True, blank=True)
    ROUmerennye_METminned_16_8 = models.FloatField(null=True, blank=True)
    ROEnergichnye_METminned_17_8 = models.FloatField(null=True, blank=True)
    ROObschaya_prodolzhitelnost_METminned_18_8 = models.FloatField(null=True, blank=True)
    ATHodba_METminned_19_8 = models.FloatField(null=True, blank=True)
    ATVelosport_METminned_20_8 = models.FloatField(null=True, blank=True)
    ATObschii_transport_METminned_21_8 = models.FloatField(null=True, blank=True)
    DSEnergichnye_METminned_22_8 = models.FloatField(null=True, blank=True)
    DSUmerennye_dvor_METminned_23_8 = models.FloatField(null=True, blank=True)
    DSUmerennye_dom_METminned_24_8 = models.FloatField(null=True, blank=True)
    DSObschaya_prodolzhitelnost_METminned_25_8 = models.FloatField(null=True, blank=True)
    ZDHodba_METminned_26_8 = models.FloatField(null=True, blank=True)
    ZDUmerennye_METminned_27_8 = models.FloatField(null=True, blank=True)
    ZDEnergichnye_METminned_28_8 = models.FloatField(null=True, blank=True)
    ZDObschee_vremya_otdyha_METminned_29_8 = models.FloatField(null=True, blank=True)
    Obschkvo_Hodba_METminned_30_8 = models.FloatField(null=True, blank=True)
    Obschkvo_Umerennye_METminned_31_8 = models.FloatField(null=True, blank=True)
    Obschkvo_Energichnye_METminned_32_8 = models.FloatField(null=True, blank=True)
    Obschocenka_METminned_33_8 = models.FloatField(null=True, blank=True)
    Sidyaschii_itog_34_8 = models.FloatField(null=True, blank=True)
    Sidya_v_den_35_8 = models.FloatField(null=True, blank=True)

class PatienDietBase(models.Model):
    ID_0_9 = models.CharField(max_length=254, null=True)
    Moloko_do_11_1_9 = models.CharField(max_length=254, null = True)
    Moloko_do_252_2_9 = models.CharField(max_length=254, null = True)
    Moloko_bolee_33_3_9 = models.CharField(max_length=254, null = True)
    Sguschenka4_4_9 = models.CharField(max_length=254, null = True)
    Kefir_do_15_5_9 = models.CharField(max_length=254, null = True)
    Kefir_do_256_6_9 = models.CharField(max_length=254, null = True)
    Kefir_bolee_37_7_9 = models.CharField(max_length=254, null = True)
    Iogurt_do_18_8_9 = models.CharField(max_length=254, null = True)
    Iogurt_do_259_9_9 = models.CharField(max_length=254, null = True)
    Iogurt_bolee_310_10_9 = models.CharField(max_length=254, null = True)
    Tvorog_do_511_11_9 = models.CharField(max_length=254, null = True)
    Tvorog_bolee_512_12_9 = models.CharField(max_length=254, null = True)
    Syrki13_13_9 = models.CharField(max_length=254, null = True)
    Tvorozhniki14_14_9 = models.CharField(max_length=254, null = True)
    Smetana_do_1515_15_9 = models.CharField(max_length=254, null = True)
    Smetana_bolee_2016_16_9 = models.CharField(max_length=254, null = True)
    Syr_myagkii17_17_9 = models.CharField(max_length=254, null = True)
    Syr_do_2518_18_9 = models.CharField(max_length=254, null = True)
    Syr_bolee_2519_19_9 = models.CharField(max_length=254, null = True)
    Margarin20_20_9 = models.CharField(max_length=254, null = True)
    Maslo_buterbr21_21_9 = models.CharField(max_length=254, null = True)
    Morozhennoe22_22_9 = models.CharField(max_length=254, null = True)
    Banany23_23_9 = models.CharField(max_length=254, null = True)
    YAgody24_24_9 = models.CharField(max_length=254, null = True)
    Kivi25_25_9 = models.CharField(max_length=254, null = True)
    Grusha26_26_9 = models.CharField(max_length=254, null = True)
    Klubnika27_27_9 = models.CharField(max_length=254, null = True)
    Suhofrukty28_28_9 = models.CharField(max_length=254, null = True)
    Izum29_29_9 = models.CharField(max_length=254, null = True)
    Ananas30_30_9 = models.CharField(max_length=254, null = True)
    YAbloko31_31_9 = models.CharField(max_length=254, null = True)
    Greipfrut32_32_9 = models.CharField(max_length=254, null = True)
    Vinograd33_33_9 = models.CharField(max_length=254, null = True)
    Mandarin34_34_9 = models.CharField(max_length=254, null = True)
    Limon35_35_9 = models.CharField(max_length=254, null = True)
    Apelsin36_36_9 = models.CharField(max_length=254, null = True)
    Persik37_37_9 = models.CharField(max_length=254, null = True)
    Sliva38_38_9 = models.CharField(max_length=254, null = True)
    Persik_v_sezon39_39_9 = models.CharField(max_length=254, null = True)
    Slivy_v_sezon40_40_9 = models.CharField(max_length=254, null = True)
    Abrikosy_v_sezon41_41_9 = models.CharField(max_length=254, null = True)
    Arbuz_v_sezon42_42_9 = models.CharField(max_length=254, null = True)
    Mandariny_v_sezon43_43_9 = models.CharField(max_length=254, null = True)
    CHereshnya_v_sezon44_44_9 = models.CharField(max_length=254, null = True)
    Klubnika_v_sezon45_45_9 = models.CharField(max_length=254, null = True)
    YAgody_v_sezon46_46_9 = models.CharField(max_length=254, null = True)
    Kapusta_svezhaya47_47_9 = models.CharField(max_length=254, null = True)
    Kapusta_prigotov48_48_9 = models.CharField(max_length=254, null = True)
    Cvetnaya_kapusta_svezhaya49_49_9 = models.CharField(max_length=254, null = True)
    Cvetnaya_kapusta_prigot50_50_9 = models.CharField(max_length=254, null = True)
    Morkov_svezhaya51_51_9 = models.CharField(max_length=254, null = True)
    Morkov_prigot52_52_9 = models.CharField(max_length=254, null = True)
    Svekla53_53_9 = models.CharField(max_length=254, null = True)
    Selderei54_54_9 = models.CharField(max_length=254, null = True)
    Ogurec55_55_9 = models.CharField(max_length=254, null = True)
    Salat_rukkol56_56_9 = models.CharField(max_length=254, null = True)
    Petrushka_ukrop57_57_9 = models.CharField(max_length=254, null = True)
    Goroh_svezhii58_58_9 = models.CharField(max_length=254, null = True)
    Goroh_prigot59_59_9 = models.CharField(max_length=254, null = True)
    Boby60_60_9 = models.CharField(max_length=254, null = True)
    Fasol61_61_9 = models.CharField(max_length=254, null = True)
    CHechevica62_62_9 = models.CharField(max_length=254, null = True)
    Ovoschnoi_salat63_63_9 = models.CharField(max_length=254, null = True)
    Okroshka64_64_9 = models.CharField(max_length=254, null = True)
    Vinegret65_65_9 = models.CharField(max_length=254, null = True)
    Zelenyi_luk_svezhii66_66_9 = models.CharField(max_length=254, null = True)
    Zelenyi_luk_prigot67_67_9 = models.CharField(max_length=254, null = True)
    Tomaty_svezhie68_68_9 = models.CharField(max_length=254, null = True)
    Tomaty_prigot69_69_9 = models.CharField(max_length=254, null = True)
    Perec_prigot70_70_9 = models.CharField(max_length=254, null = True)
    Griby71_71_9 = models.CharField(max_length=254, null = True)
    Kapusta_kvashenaya72_72_9 = models.CharField(max_length=254, null = True)
    SHpinat73_73_9 = models.CharField(max_length=254, null = True)
    Kabachok74_74_9 = models.CharField(max_length=254, null = True)
    Tykva75_75_9 = models.CharField(max_length=254, null = True)
    Kukuruza76_76_9 = models.CharField(max_length=254, null = True)
    Goroh_kons77_77_9 = models.CharField(max_length=254, null = True)
    Marinady78_78_9 = models.CharField(max_length=254, null = True)
    Baklazhan79_79_9 = models.CharField(max_length=254, null = True)
    Brokkoli80_80_9 = models.CharField(max_length=254, null = True)
    Tykva_v_sezon81_81_9 = models.CharField(max_length=254, null = True)
    Kabachok_v_sezon82_82_9 = models.CharField(max_length=254, null = True)
    Perec_v_sezon83_83_9 = models.CharField(max_length=254, null = True)
    Redis_v_sezon84_84_9 = models.CharField(max_length=254, null = True)
    Griby_v_sezon85_85_9 = models.CharField(max_length=254, null = True)
    Kapusta_kvashenaya_v_sezon86_86_9 = models.CharField(max_length=254, null = True)
    YAica87_87_9 = models.CharField(max_length=254, null = True)
    Kurica_s_kozhei88_88_9 = models.CharField(max_length=254, null = True)
    Kurica_bez_kozhi89_89_9 = models.CharField(max_length=254, null = True)
    Myaso_v_slozhnom_blude90_90_9 = models.CharField(max_length=254, null = True)
    Tush_Govyadina_gulyash91_91_9 = models.CharField(max_length=254, null = True)
    Steik_iz_govyadiny92_92_9 = models.CharField(max_length=254, null = True)
    Kotleta93_93_9 = models.CharField(max_length=254, null = True)
    Svinina_tushenaya94_94_9 = models.CharField(max_length=254, null = True)
    Svinina_zharenaya95_95_9 = models.CharField(max_length=254, null = True)
    Baranina96_96_9 = models.CharField(max_length=254, null = True)
    Ryba_zharenaya_sup97_97_9 = models.CharField(max_length=254, null = True)
    Ryba_vyalenaya_solenaya98_98_9 = models.CharField(max_length=254, null = True)
    Moreprodukty99_99_9 = models.CharField(max_length=254, null = True)
    Pirozhki_s_myasom100_100_9 = models.CharField(max_length=254, null = True)
    Kurinnyi_rulet101_101_9 = models.CharField(max_length=254, null = True)
    Sosiski102_102_9 = models.CharField(max_length=254, null = True)
    Kolbasa_varenaya103_103_9 = models.CharField(max_length=254, null = True)
    Kolbasa_kopchenaya104_104_9 = models.CharField(max_length=254, null = True)
    Buzhenina_okorok_vetchina105_105_9 = models.CharField(max_length=254, null = True)
    Salo106_106_9 = models.CharField(max_length=254, null = True)
    Subprodukty107_107_9 = models.CharField(max_length=254, null = True)
    Kartofel108_108_9 = models.CharField(max_length=254, null = True)
    Pasta109_109_9 = models.CharField(max_length=254, null = True)
    Belyi_hleb110_110_9 = models.CharField(max_length=254, null = True)
    CHernyi_hleb111_111_9 = models.CharField(max_length=254, null = True)
    Seryi_hleb112_112_9 = models.CharField(max_length=254, null = True)
    Ris113_113_9 = models.CharField(max_length=254, null = True)
    Kartofel_vo_friture114_114_9 = models.CharField(max_length=254, null = True)
    Vareniki115_115_9 = models.CharField(max_length=254, null = True)
    Pelmeni116_116_9 = models.CharField(max_length=254, null = True)
    Picca117_117_9 = models.CharField(max_length=254, null = True)
    Grechnevaya_krupa118_118_9 = models.CharField(max_length=254, null = True)
    Mannaya_kasha119_119_9 = models.CharField(max_length=254, null = True)
    Hlopya120_120_9 = models.CharField(max_length=254, null = True)
    Ovsyannaya_kruppa121_121_9 = models.CharField(max_length=254, null = True)
    Psheno122_122_9 = models.CharField(max_length=254, null = True)
    Prochie_zlaki123_123_9 = models.CharField(max_length=254, null = True)
    Borsch124_124_9 = models.CharField(max_length=254, null = True)
    Bulon125_125_9 = models.CharField(max_length=254, null = True)
    Rassolnik126_126_9 = models.CharField(max_length=254, null = True)
    Sup_s_ovoschami127_127_9 = models.CharField(max_length=254, null = True)
    Gribnoi_sup128_128_9 = models.CharField(max_length=254, null = True)
    Gorohovyi_sup129_129_9 = models.CharField(max_length=254, null = True)
    Kurinnyi_sup_s_lapshoi130_130_9 = models.CharField(max_length=254, null = True)
    Soki131_131_9 = models.CharField(max_length=254, null = True)
    Kofe132_132_9 = models.CharField(max_length=254, null = True)
    CHai133_133_9 = models.CharField(max_length=254, null = True)
    Voda134_134_9 = models.CharField(max_length=254, null = True)
    Gazirovka135_135_9 = models.CharField(max_length=254, null = True)
    Bezalkogolnye_napitki136_136_9 = models.CharField(max_length=254, null = True)
    Pivo137_137_9 = models.CharField(max_length=254, null = True)
    Vino138_138_9 = models.CharField(max_length=254, null = True)
    Vodka_konyak_liker139_139_9 = models.CharField(max_length=254, null = True)
    Kvas140_140_9 = models.CharField(max_length=254, null = True)
    Bliny141_141_9 = models.CharField(max_length=254, null = True)
    Bulochka142_142_9 = models.CharField(max_length=254, null = True)
    Sushki_baranki143_143_9 = models.CharField(max_length=254, null = True)
    Konfety_shokolad144_144_9 = models.CharField(max_length=254, null = True)
    Konfety_karamel145_145_9 = models.CharField(max_length=254, null = True)
    Tort146_146_9 = models.CharField(max_length=254, null = True)
    Halva147_147_9 = models.CharField(max_length=254, null = True)
    Pechene148_148_9 = models.CharField(max_length=254, null = True)
    Med_dzhem_varene149_149_9 = models.CharField(max_length=254, null = True)
    SHokolad150_150_9 = models.CharField(max_length=254, null = True)
    Biskvit151_151_9 = models.CharField(max_length=254, null = True)
    Pryaniki152_152_9 = models.CharField(max_length=254, null = True)
    Pastila_zefir153_153_9 = models.CharField(max_length=254, null = True)
    Vafli154_154_9 = models.CharField(max_length=254, null = True)
    CHipsy155_155_9 = models.CharField(max_length=254, null = True)
    Suhariki156_156_9 = models.CharField(max_length=254, null = True)
    Orehi157_157_9 = models.CharField(max_length=254, null = True)
    Maionez158_158_9 = models.CharField(max_length=254, null = True)
    Ketchup159_159_9 = models.CharField(max_length=254, null = True)
    Soevyi_sous160_160_9 = models.CharField(max_length=254, null = True)
    Vitaminy_v_tabletkah161_161_9 = models.FloatField(null=True, blank=True)
    Mineraly_v_tabletkah162_162_9 = models.FloatField(null=True, blank=True)
    Vitamin_A163_163_9 = models.CharField(max_length=254, null = True)
    Vitamin_D164_164_9 = models.CharField(max_length=254, null = True)
    Vitamin_E165_165_9 = models.CharField(max_length=254, null = True)
    Vitamin_V166_166_9 = models.CharField(max_length=254, null = True)
    Vitamin_C167_167_9 = models.CharField(max_length=254, null = True)
    Kalcii168_168_9 = models.CharField(max_length=254, null = True)
    ZHelezo169_169_9 = models.CharField(max_length=254, null = True)
    Cink170_170_9 = models.CharField(max_length=254, null = True)
    Iod171_171_9 = models.CharField(max_length=254, null = True)
    Magnii172_172_9 = models.CharField(max_length=254, null = True)
    Rybii_zhir173_173_9 = models.CharField(max_length=254, null = True)
    Polivitaminy174_174_9 = models.CharField(max_length=254, null = True)
    Soevoe_maslo175_175_9 = models.CharField(max_length=254, null = True)
    Kukuruznoe_maslo176_176_9 = models.CharField(max_length=254, null = True)
    Rastitelnoe_maslo177_177_9 = models.CharField(max_length=254, null = True)
    Podsolnechnoe_maslo178_178_9 = models.CharField(max_length=254, null = True)
    Rapsovoe_maslo179_179_9 = models.CharField(max_length=254, null = True)
    Hlopkovoe_maslo180_180_9 = models.CharField(max_length=254, null = True)
    Olivkovoe_maslo181_181_9 = models.CharField(max_length=254, null = True)
    Slivochnoe_maslo182_182_9 = models.CharField(max_length=254, null = True)
    Pitanie_v_restoranah183_183_9 = models.CharField(max_length=254, null = True)
    Dobavlenie_soli184_184_9 = models.CharField(max_length=254, null = True)

class PatientInternet(models.Model):
    ID_0_10 = models.CharField(max_length=254, null=True)
    Kuryat_bolnica1_1_10 = models.CharField(max_length=254, null=True)
    Kuryat_ostanovka1_2_10 = models.CharField(max_length=254, null=True)
    Kuryat_restoran1_3_10 = models.CharField(max_length=254, null=True)
    Kuryat_bar1_4_10 = models.CharField(max_length=254, null=True)
    Kuryat_biblioteka1_5_10 = models.CharField(max_length=254, null=True)
    Kuryat_pravitelstvo1_6_10 = models.CharField(max_length=254, null=True)
    Kuryat_rabota1_7_10 = models.CharField(max_length=254, null=True)
    Kuryat_dom1_8_10 = models.CharField(max_length=254, null=True)
    Mogut_kurit_bolnica2_9_10 = models.CharField(max_length=254, null=True)
    Mogut_kurit_ostanovka2_10_10 = models.CharField(max_length=254, null=True)
    Mogut_kurit_restoran2_11_10 = models.CharField(max_length=254, null=True)
    Mogut_kurit_bar2_12_10 = models.CharField(max_length=254, null=True)
    Mogut_kurit_biblioteka2_13_10 = models.CharField(max_length=254, null=True)
    Mogut_kurit_pravitelstvo2_14_10 = models.CharField(max_length=254, null=True)
    Mogut_kurit_rabota2_15_10 = models.CharField(max_length=254, null=True)
    Mogut_kurit_dom2_16_10 = models.CharField(max_length=254, null=True)
    Reklama_sigaret_plakaty3_17_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_obyavleniya3_18_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_TV3_19_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_radio3_20_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_kino3_21_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_SMI3_22_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_meropriyatiya3_23_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_tovary3_24_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_Internet3_25_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_akterov3_26_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_obrazcy_tovarov3_27_10 = models.FloatField(null=True, blank=True)
    Reklama_sigaret_kupony3_28_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_plakaty4_29_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_obyavleniya4_30_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_TV4_31_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_radio4_32_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_kino4_33_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_SMI4_34_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_meropriyatiya4_35_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_tovary4_36_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_Internet4_37_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_obrazcy_tovarov4_38_10 = models.FloatField(null=True, blank=True)
    Reklama_otkaza_sigaret_kupony4_39_10 = models.FloatField(null=True, blank=True)
    Pokupka_podrostkami_sigaret5_40_10 = models.CharField(max_length=254, null=True)
    a_Odobrenie_kuryaschih_detei6_41_10 = models.CharField(max_length=254, null=True)
    b_Odobrenie_kuryaschih_podrostkov6_42_10 = models.CharField(max_length=254, null=True)
    s_Odobrenie_kuryaschih_zhenschin6_43_10 = models.CharField(max_length=254, null=True)
    d_Odobrenie_kuryaschih_muzhchin6_44_10 = models.CharField(max_length=254, null=True)
    e_Odobrenie_podrostkov_bidi6_45_10 = models.CharField(max_length=254, null=True)
    f_Odobrenie_zhenschin_bidi6_46_10 = models.CharField(max_length=254, null=True)
    g_Odobrenie_muzhchin_bidi6_47_10 = models.CharField(max_length=254, null=True)
    h_Odobrenie_podrostkov_kalyan6_48_10 = models.CharField(max_length=254, null=True)
    i_Odobrenie_zhenschin_kalyan6_49_10 = models.CharField(max_length=254, null=True)
    j_Odobrenie_muzhchin_kalyan6_50_10 = models.CharField(max_length=254, null=True)
    a_Zapret_kureniya_v_obsch_mestah7_51_10 = models.CharField(max_length=254, null=True)
    b_Zapret_reklamy_sigaret7_52_10 = models.CharField(max_length=254, null=True)
    s_Preduprezhdenie_na_pachkah_sigaret7_53_10 = models.CharField(max_length=254, null=True)
    d_Zapret_prodazh_sigaret_detyam7_54_10 = models.CharField(max_length=254, null=True)
    e_Zapret_kureniya_detmi7_55_10 = models.CharField(max_length=254, null=True)
    f_Ogranichenie_prodazh_sigaret7_56_10 = models.CharField(max_length=254, null=True)
    g_Programmy_otkaza_ot_kureniya7_57_10 = models.CharField(max_length=254, null=True)
    a_Kurenie_HZL8_58_10 = models.CharField(max_length=254, null=True)
    b_Kureniezabolevaniya_serdca8_59_10 = models.CharField(max_length=254, null=True)
    s_Kureniediabet8_60_10 = models.CharField(max_length=254, null=True)
    d_Kurenieinsult8_61_10 = models.CharField(max_length=254, null=True)
    e_Kurenieartrit8_62_10 = models.CharField(max_length=254, null=True)
    f_Kurenierak_legkih8_63_10 = models.CharField(max_length=254, null=True)
    g_KurenieRak_gorla8_64_10 = models.CharField(max_length=254, null=True)
    h_Kureniepassivnye_kurilschiki8_65_10 = models.CharField(max_length=254, null=True)
    i_Kurenieprezhdevremennye_rody8_66_10 = models.CharField(max_length=254, null=True)
    j_Kureniedeti_s_malym_vesom8_67_10 = models.CharField(max_length=254, null=True)
    Reklama_nezdor_pitanie_plakaty9_68_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_obyavleniya9_69_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_TV9_70_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_radio9_71_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_kino9_72_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_SMI9_73_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_meropriyatiya9_74_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_tovary9_75_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_Internet9_76_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_obrazcy_tovarov9_77_10 = models.FloatField(null=True, blank=True)
    Reklama_nezdor_pitanie_kupony9_78_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_plakaty10_79_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_obyavleniya10_80_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_TV10_81_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_radio10_82_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_kino10_83_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_SMI10_84_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_meropriyatiya10_85_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_tovary10_86_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_Internet10_87_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_obrazcy_tovarov10_88_10 = models.FloatField(null=True, blank=True)
    Reklama_gaz_napitkov_kupony10_89_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_plakaty11_90_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_obyavleniya11_91_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_TV11_92_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_radio11_93_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_kino11_94_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_SMI11_95_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_meropriyatiya11_96_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_tovary11_97_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_Internet11_98_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_obrazcy_tovarov11_99_10 = models.FloatField(null=True, blank=True)
    Reklama_alkogolya_kupony11_100_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_plakaty12_101_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_obyavleniya12_102_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_TV12_103_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_radio12_104_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_kino12_105_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_SMI12_106_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_meropriyatiya12_107_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_tovary12_108_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_Internet12_109_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_obrazcy_tovarov12_110_10 = models.FloatField(null=True, blank=True)
    Reklama_fruktov_kupony12_111_10 = models.FloatField(null=True, blank=True)
    Reklama_diety_plakaty13_112_10 = models.FloatField(null=True, blank=True)
    Reklama_diety_obyavleniya13_113_10 = models.FloatField(null=True, blank=True)
    Reklama_diety_TV13_114_10 = models.FloatField(null=True, blank=True)
    Reklama_diety_radio13_115_10 = models.FloatField(null=True, blank=True)
    Reklama_diety_kino13_116_10 = models.FloatField(null=True, blank=True)
    Reklama_diety_SMI13_117_10 = models.FloatField(null=True, blank=True)
    Reklama_diety_meropriyatiya13_118_10 = models.FloatField(null=True, blank=True)
    Reklama_diety_tovary13_119_10 = models.FloatField(null=True, blank=True)
    Reklama_diety_Internet13_120_10 = models.FloatField(null=True, blank=True)
    Reklama_fiz_aktivnosti_plakaty14_121_10 = models.FloatField(null=True, blank=True)
    Reklama_fiz_aktivnosti_obyavleniya14_122_10 = models.FloatField(null=True, blank=True)
    Reklama_fiz_aktivnosti_TV14_123_10 = models.FloatField(null=True, blank=True)
    Reklama_fiz_aktivnosti_radio14_124_10 = models.FloatField(null=True, blank=True)
    Reklama_fiz_aktivnosti_kino14_125_10 = models.FloatField(null=True, blank=True)
    Reklama_fiz_aktivnosti_SMI14_126_10 = models.FloatField(null=True, blank=True)
    Reklama_fiz_aktivnosti_meropriyatiya14_127_10 = models.FloatField(null=True, blank=True)
    Reklama_fiz_aktivnosti_tovary14_128_10 = models.FloatField(null=True, blank=True)
    Reklama_fiz_aktivnosti_Internet14_129_10 = models.FloatField(null=True, blank=True)
    Reklama_polzy_produktov_plakaty15_130_10 = models.FloatField(null=True, blank=True)
    Reklama_polzy_produktov_obyavleniya15_131_10 = models.FloatField(null=True, blank=True)
    Reklama_polzy_produktov_TV15_132_10 = models.FloatField(null=True, blank=True)
    Reklama_polzy_produktov_radio15_133_10 = models.FloatField(null=True, blank=True)
    Reklama_polzy_produktov_kino15_134_10 = models.FloatField(null=True, blank=True)
    Reklama_polzy_produktov_SMI15_135_10 = models.FloatField(null=True, blank=True)
    Reklama_polzy_produktov_meropriyatiya15_136_10 = models.FloatField(null=True, blank=True)
    Reklama_polzy_produktov_tovary15_137_10 = models.FloatField(null=True, blank=True)
    Reklama_polzy_produktov_Internet15_138_10 = models.FloatField(null=True, blank=True)
    Obsch_Davlenie_a16_139_10 = models.CharField(max_length=254, null=True)
    Obsch_Davlenie_b16_140_10 = models.CharField(max_length=254, null=True)
    Obsch_Davlenie_c16_141_10 = models.CharField(max_length=254, null=True)
    Obsch_Davlenie_d16_142_10 = models.CharField(max_length=254, null=True)
    Obsch_Davlenie_e16_143_10 = models.CharField(max_length=254, null=True)
    Obsch_Davlenie_f16_144_10 = models.CharField(max_length=254, null=True)
    Izvestno_li_o_nalichii_a17_145_10 = models.CharField(max_length=254, null=True)
    Izvestno_li_o_nalichii_b17_146_10 = models.CharField(max_length=254, null=True)
    Izvestno_li_o_nalichii_c17_147_10 = models.CharField(max_length=254, null=True)
    Izvestno_li_o_nalichii_d17_148_10 = models.CharField(max_length=254, null=True)
    Izvestno_li_o_nalichii_e17_149_10 = models.CharField(max_length=254, null=True)
    Izvestno_li_o_nalichii_f17_150_10 = models.CharField(max_length=254, null=True)
    Izvestno_li_o_nalichii_g17_151_10 = models.CharField(max_length=254, null=True)
    Izvestno_li_o_nalichii_h17_152_10 = models.CharField(max_length=254, null=True)
    SSZ_uvelich_Fiz_aktivnosti18_153_10 = models.CharField(max_length=254, null=True)
    SSZ_frukty18_154_10 = models.CharField(max_length=254, null=True)
    SSZ_ovoschi18_155_10 = models.CharField(max_length=254, null=True)
    SSZ_myaso18_156_10 = models.CharField(max_length=254, null=True)
    SSZ_kofe18_157_10 = models.CharField(max_length=254, null=True)
    SSZ_molochnye_produkty18_158_10 = models.CharField(max_length=254, null=True)
    SSZ_ryba18_159_10 = models.CharField(max_length=254, null=True)
    SSZ_kurenie18_160_10 = models.CharField(max_length=254, null=True)
    SSZ_snizhenie_zhirov18_161_10 = models.CharField(max_length=254, null=True)
    SSZ_snizhenie_soli18_162_10 = models.CharField(max_length=254, null=True)
    SSZ_uvelichenie_vesa18_163_10 = models.CharField(max_length=254, null=True)
    Markirovka_mestnye_produkty19_164_10 = models.CharField(max_length=254, null=True)
    Markirovka_importnye_produkty19_165_10 = models.CharField(max_length=254, null=True)
    Zamechaniya_kuryaschim_detyam20_166_10 = models.CharField(max_length=254, null=True)
    Zamechaniya_kuryaschim_podrostkam20_167_10 = models.CharField(max_length=254, null=True)
    Zamechaniya_nezdorovoi_edy_deti21_168_10 = models.CharField(max_length=254, null=True)
    Zamechaniya_nezdorovaya_eda_podrostki21_169_10 = models.CharField(max_length=254, null=True)
    Sovety_fiz_aktivnosti_deti22_170_10 = models.CharField(max_length=254, null=True)
    Sovety_fiz_aktivnosti_podrostki22_171_10 = models.CharField(max_length=254, null=True)
    Pomosch_sosedyam23_172_10 = models.CharField(max_length=254, null=True)
    Rekomendacii_po_otkazu_ot_kureniya27_173_10 = models.CharField(max_length=254, null=True)
    Poseschenie_shkoly28_174_10 = models.FloatField(null=True, blank=True)
    Uroven_obrazovaniya29_175_10 = models.CharField(max_length=254, null=True)
    Let_obucheniya30_176_10 = models.FloatField(null=True, blank=True)
    Pyat_znakomyh_kuryat31_177_10 = models.FloatField(null=True, blank=True)
    Pyat_znakomyh_alkogol31_178_10 = models.FloatField(null=True, blank=True)
    Pyat_znakomyh_ozhirenie31_179_10 = models.FloatField(null=True, blank=True)
    a_Sobstvennye_frukty_i_ovoschi32_180_10 = models.FloatField(null=True, blank=True)
    b_Dolya_fruktov_i_ovoschei32_181_10 = models.CharField(max_length=254, null=True)
    Kak_dobiraetes_do_magazina33_182_10 = models.CharField(max_length=254, null=True)
    Vremya_do_magazina34_183_10 = models.FloatField(null=True, blank=True)
    Adres_magazina35_184_10 = models.CharField(max_length=254, null=True)
    Kod_magazina_EPOCH_136_185_10 = models.CharField(max_length=254, null=True)
    a_Mesto_raboty39_186_10 = models.CharField(max_length=254, null=True)
    b_Indeks_raboty39_187_10 = models.CharField(max_length=254, null=True)
    c_Rasstoyanie_do_raboty39_188_10 = models.FloatField(null=True, blank=True)
    d_Vremya_do_raboty39_189_10 = models.FloatField(null=True, blank=True)
    Kak_dobiraetes_do_raboty40_190_10 = models.CharField(max_length=254, null=True)
    CHasov_v_nedelu_na_rabote41_191_10 = models.FloatField(null=True, blank=True)
    a_Internet_doma43_192_10 = models.FloatField(null=True, blank=True)
    b_Internet_na_rabote43_193_10 = models.FloatField(null=True, blank=True)
    c_Internet_v_raione_besplatnyi43_194_10 = models.FloatField(null=True, blank=True)
    d_Internet_v_raione_platnyi43_195_10 = models.FloatField(null=True, blank=True)
    e_Internet_u_druzei43_196_10 = models.FloatField(null=True, blank=True)
    f_Internet_inoe_mesto43_197_10 = models.FloatField(null=True, blank=True)
    g_Interneta_NET43_198_10 = models.FloatField(null=True, blank=True)



class PatientDiet(models.Model):
    ID_0_11 = models.CharField(max_length=254, null = True)
    Produkt_0_11 = models.CharField(max_length=254, null = True)
    Snyatoe_moloko_do_01_zhirnosti_200g1_1_11 = models.CharField(max_length=254, null=True)
    Moloko_nizkozhirovoe_12_25_200g2_2_11 = models.CharField(max_length=254, null=True)
    Celnoe_moloko_svyshe_3_200g3_3_11 = models.CharField(max_length=254, null=True)
    Sguschennoe_moloko_30g4_4_11 = models.CharField(max_length=254, null=True)
    Kefir_ryazhenka_prostokvasha_do_01_200g5_5_11 = models.CharField(max_length=254, null=True)
    Kefir_ryazhenka_prostokvasha_12_25_200g6_6_11 = models.CharField(max_length=254, null=True)
    Kefir_ryazhenka_prostokvasha_svyshe_3_200g7_7_11 = models.CharField(max_length=254, null=True)
    Iogurt_do_01_125g8_8_11 = models.CharField(max_length=254, null=True)
    Iogurt_12_25_125g9_9_11 = models.CharField(max_length=254, null=True)
    Iogurt_svyshe_3_125g10_10_11 = models.CharField(max_length=254, null=True)
    Tvorog_049_100g11_11_11 = models.CharField(max_length=254, null=True)
    Tvorog_5_i_vyshe_100g12_12_11 = models.CharField(max_length=254, null=True)
    Syrki_tvorozhnye_tvorozhnaya_massa_100g13_13_11 = models.CharField(max_length=254, null=True)
    Bluda_mz_tvoroga_syrniki_zapekanka_200g14_14_11 = models.CharField(max_length=254, null=True)
    Smetana_1015_20g15_15_11 = models.CharField(max_length=254, null=True)
    Smetana_svyshe_20_slivki_20g16_16_11 = models.CharField(max_length=254, null=True)
    Syr_brynza_mocarella_100g17_17_11 = models.CharField(max_length=254, null=True)
    Syr_5249_30g18_18_11 = models.CharField(max_length=254, null=True)
    Syr_svyshe_25_30g19_19_11 = models.CharField(max_length=254, null=True)
    Margarin_dlya_buterbroda_5g20_20_11 = models.CharField(max_length=254, null=True)
    Maslo_dlya_buterbroda_5g21_21_11 = models.CharField(max_length=254, null=True)
    Morozhenoe_100g22_22_11 = models.CharField(max_length=254, null=True)
    Banany_100g23_23_11 = models.CharField(max_length=254, null=True)
    a_chernika_smorodina_svezhie_zamorozhennye_konserv_100g24_24_11 = models.CharField(max_length=254, null=True)
    Kivi_1_sht25_25_11 = models.CharField(max_length=254, null=True)
    Grusha_130_g26_26_11 = models.CharField(max_length=254, null=True)
    Klubnika_svezhaya_200g27_27_11 = models.CharField(max_length=254, null=True)
    Suhofrukty_yabloki_abrikosy_100g28_28_11 = models.CharField(max_length=254, null=True)
    Izum_10g29_29_11 = models.CharField(max_length=254, null=True)
    Ananas_100g30_30_11 = models.CharField(max_length=254, null=True)
    YAbloko_150g31_31_11 = models.CharField(max_length=254, null=True)
    Greipfrut_200g32_32_11 = models.CharField(max_length=254, null=True)
    Vinograd_200g33_33_11 = models.CharField(max_length=254, null=True)
    Mandarin_80g34_34_11 = models.CharField(max_length=254, null=True)
    Limon_80g35_35_11 = models.CharField(max_length=254, null=True)
    Apelsin_150g36_36_11 = models.CharField(max_length=254, null=True)
    Persik_90g37_37_11 = models.CharField(max_length=254, null=True)
    Sliva_40g38_38_11 = models.CharField(max_length=254, null=True)
    Persik_v_sezon_9g39_39_11 = models.CharField(max_length=254, null=True)
    Slivy_v_sezon_40g40_40_11 = models.CharField(max_length=254, null=True)
    Abrikosy_v_sezon_20u41_41_11 = models.CharField(max_length=254, null=True)
    Arbuz_v_sezon_200g42_42_11 = models.CharField(max_length=254, null=True)
    Mandariny_v_sezon_80g43_43_11 = models.CharField(max_length=254, null=True)
    CHereshnya_v_sezon_150g44_44_11 = models.CharField(max_length=254, null=True)
    Klubnika_v_sezon_200g45_45_11 = models.CharField(max_length=254, null=True)
    YAgody_v_sezon_200g46_46_11 = models.CharField(max_length=254, null=True)
    Kapusta_svezhaya_50g47_47_11 = models.CharField(max_length=254, null=True)
    Kapusta_prigotovlennaya_100g48_48_11 = models.CharField(max_length=254, null=True)
    Cvetnaya_kapusta_svezhaya_50g49_49_11 = models.CharField(max_length=254, null=True)
    Cvetnaya_kapusta_prigotovlennaya_100g50_50_11 = models.CharField(max_length=254, null=True)
    Morkov_svezhaya_50g51_51_11 = models.CharField(max_length=254, null=True)
    Morkov_prigotovlennaya_100g52_52_11 = models.CharField(max_length=254, null=True)
    Svekla_prigotovlennaya_100g53_53_11 = models.CharField(max_length=254, null=True)
    Selderei_stebel_10sm54_54_11 = models.CharField(max_length=254, null=True)
    Ogurec_svezhii_70g55_55_11 = models.CharField(max_length=254, null=True)
    Listya_salata_rukkola_salat_Aisberg_30g56_56_11 = models.CharField(max_length=254, null=True)
    Salatnye_travy_ukrop_petrushka_kinza_40g57_57_11 = models.CharField(max_length=254, null=True)
    Goroh_svezhii_100g58_58_11 = models.CharField(max_length=254, null=True)
    Goroh_prigotovlennyi_100g59_59_11 = models.CharField(max_length=254, null=True)
    Boby_struchkovaya_fasol_prigotovlennye_100g60_60_11 = models.CharField(max_length=254, null=True)
    Fasol_prigotovlennaya_konserv_100g61_61_11 = models.CharField(max_length=254, null=True)
    CHechevica_100g62_62_11 = models.CharField(max_length=254, null=True)
    Ovoschnoi_salat_svezhii_100g63_63_11 = models.CharField(max_length=254, null=True)
    Okroshka_ovoschi_100g64_64_11 = models.CharField(max_length=254, null=True)
    Vinegret_200g65_65_11 = models.CharField(max_length=254, null=True)
    Zelenyi_luk_svezhii_50g66_66_11 = models.CharField(max_length=254, null=True)
    Zelenyi_luk_prigotovlennyi_12_chashki67_67_11 = models.CharField(max_length=254, null=True)
    Tomaty_svezhie_100g68_68_11 = models.CharField(max_length=254, null=True)
    Tomaty_prigotovlennye_12_chashki69_69_11 = models.CharField(max_length=254, null=True)
    Perec_prigotovlennyi_150g70_70_11 = models.CharField(max_length=254, null=True)
    Griby_zharenye_150g71_71_11 = models.CharField(max_length=254, null=True)
    Kapusta_kvashenaya_150g72_72_11 = models.CharField(max_length=254, null=True)
    SHpinat_prigotovlennyi_200g73_73_11 = models.CharField(max_length=254, null=True)
    Kabachok_prigotovlennyi_200g74_74_11 = models.CharField(max_length=254, null=True)
    Tykva_prigotovlennaya_100g75_75_11 = models.CharField(max_length=254, null=True)
    Sladkaya_kukuruza_konserv_sushenaya_250g76_76_11 = models.CharField(max_length=254, null=True)
    Zelenyi_goroh_konserv_sushenyi_200g77_77_11 = models.CharField(max_length=254, null=True)
    Marinovannye_ovoschi_ogurec_tomaty_i_dr_200g78_78_11 = models.CharField(max_length=254, null=True)
    Baklazhan_prigotovlennyi_200g79_79_11 = models.CharField(max_length=254, null=True)
    Brokkoli_100g80_80_11 = models.CharField(max_length=254, null=True)
    Tykva_v_sezon_100g81_81_11 = models.CharField(max_length=254, null=True)
    Kabachok_v_sezon_200g82_82_11 = models.CharField(max_length=254, null=True)
    Perec_v_sezon_50g83_83_11 = models.CharField(max_length=254, null=True)
    Redis_v_sezon_60g84_84_11 = models.CharField(max_length=254, null=True)
    Griby_v_sezon_50g85_85_11 = models.CharField(max_length=254, null=True)
    Kapusta_kvashenaya_v_sezon_100g86_86_11 = models.CharField(max_length=254, null=True)
    YAica_47g87_87_11 = models.CharField(max_length=254, null=True)
    Kurica_ili_indeika_s_kozhei_120g88_88_11 = models.CharField(max_length=254, null=True)
    Kurica_ili_indeika_bez_kozhi_120g89_89_11 = models.CharField(max_length=254, null=True)
    Govyadina_svinina_kozlyatina_ili_yagnyatina_120g90_90_11 = models.CharField(max_length=254, null=True)
    Tushenaya_govyadina_gulyash_120g91_91_11 = models.CharField(max_length=254, null=True)
    Steik_iz_govyadiny_120g92_92_11 = models.CharField(max_length=254, null=True)
    Kotleta_60g93_93_11 = models.CharField(max_length=254, null=True)
    Svinina_tushenaya_120g94_94_11 = models.CharField(max_length=254, null=True)
    Svinina_zharenaya_120g95_95_11 = models.CharField(max_length=254, null=True)
    Baranina_tushenaya_120g96_96_11 = models.CharField(max_length=254, null=True)
    Ryba_zharenaya_ili_tushenaya_sup_120g97_97_11 = models.CharField(max_length=254, null=True)
    Ryba_vyalenaya_solenaya_kopchenaya_100g98_98_11 = models.CharField(max_length=254, null=True)
    Moreprodukty_120g99_99_11 = models.CharField(max_length=254, null=True)
    Pirozhki_s_myasom_belyashi_chebureki_100g100_100_11 = models.CharField(max_length=254, null=True)
    Kurinyi_rulet_vetchina_iz_indeiki_30g101_101_11 = models.CharField(max_length=254, null=True)
    Sosiski_svinye_i_govyazhi_100g102_102_11 = models.CharField(max_length=254, null=True)
    Kolbasa_varenaya_30g103_103_11 = models.CharField(max_length=254, null=True)
    Kolbasa_kopchenaya_30g104_104_11 = models.CharField(max_length=254, null=True)
    Buzhenina_okorok_vetchina_svinina_govyadina_50g105_105_11 = models.CharField(max_length=254, null=True)
    Salo_svinoe_30g106_106_11 = models.CharField(max_length=254, null=True)
    Subprodukty_pechen_yazyk_serdce_100g107_107_11 = models.CharField(max_length=254, null=True)
    Kartofel_zharenyi_varenyi_pure_150g108_108_11 = models.CharField(max_length=254, null=True)
    Pasta_spagetti_150g109_109_11 = models.CharField(max_length=254, null=True)
    Belyi_hleb_30g110_110_11 = models.CharField(max_length=254, null=True)
    CHernyi_hleb_30g111_111_11 = models.CharField(max_length=254, null=True)
    Seryi_hleb_s_otrubyami_40g112_112_11 = models.CharField(max_length=254, null=True)
    Belyi_ris_prigotovlennyi_150g113_113_11 = models.CharField(max_length=254, null=True)
    Kartofel_vo_friture_120g114_114_11 = models.CharField(max_length=254, null=True)
    Vareniki_200g115_115_11 = models.CharField(max_length=254, null=True)
    Pelmeni_200g116_116_11 = models.CharField(max_length=254, null=True)
    Picca_200g117_117_11 = models.CharField(max_length=254, null=True)
    Grechnevaya_krupa_150g118_118_11 = models.CharField(max_length=254, null=True)
    Mannaya_kasha_150g119_119_11 = models.CharField(max_length=254, null=True)
    Hlopya_tipa_Kornfleks_25g120_120_11 = models.CharField(max_length=254, null=True)
    Ovsyanaya_krupa_150g121_121_11 = models.CharField(max_length=254, null=True)
    Psheno_150g122_122_11 = models.CharField(max_length=254, null=True)
    Prochie_zlaki_prigotovlennye_150g123_123_11 = models.CharField(max_length=254, null=True)
    Borsch_250ml124_124_11 = models.CharField(max_length=254, null=True)
    Bulon_250ml125_125_11 = models.CharField(max_length=254, null=True)
    Rassolnik_250ml126_126_11 = models.CharField(max_length=254, null=True)
    Sup_s_ovoschami_250ml127_127_11 = models.CharField(max_length=254, null=True)
    Gribnoi_sup_250ml128_128_11 = models.CharField(max_length=254, null=True)
    Gorohovyi_sup_250ml129_129_11 = models.CharField(max_length=254, null=True)
    Kurinyi_sup_s_lapshoi_250ml130_130_11 = models.CharField(max_length=254, null=True)
    Fruktovye_soki_200ml131_131_11 = models.CharField(max_length=254, null=True)
    Kofe_250ml132_132_11 = models.CharField(max_length=254, null=True)
    CHai_ne_travyanoi_250ml133_133_11 = models.CharField(max_length=254, null=True)
    evaya_mineralnaya_travyanoi_chai_fruktovyi_chai_200ml134_134_11 = models.CharField(max_length=254, null=True)
    kola_pepsikola_i_pr_saharosoderzhaschie_napitki_250ml135_135_11 = models.CharField(max_length=254, null=True)
    Nizkokaloriinye_bezalkogolnye_napitki_250ml136_136_11 = models.CharField(max_length=254, null=True)
    Pivo_300ml137_137_11 = models.CharField(max_length=254, null=True)
    Vino_150ml138_138_11 = models.CharField(max_length=254, null=True)
    Vodka_konyak_liker_100ml139_139_11 = models.CharField(max_length=254, null=True)
    Kvas_200ml140_140_11 = models.CharField(max_length=254, null=True)
    Bliny_30g141_141_11 = models.CharField(max_length=254, null=True)
    Bulochka_sdobnaya_200g142_142_11 = models.CharField(max_length=254, null=True)
    Sushki_baranki_100g143_143_11 = models.CharField(max_length=254, null=True)
    Konfety_shokoladnye_44g144_144_11 = models.CharField(max_length=254, null=True)
    Konfety_karamel_10g145_145_11 = models.CharField(max_length=254, null=True)
    Tort_120g146_146_11 = models.CharField(max_length=254, null=True)
    Halva_30g147_147_11 = models.CharField(max_length=254, null=True)
    Pechene_15g148_148_11 = models.CharField(max_length=254, null=True)
    Med_dzhem_varene_6g149_149_11 = models.CharField(max_length=254, null=True)
    SHokolad_50g150_150_11 = models.CharField(max_length=254, null=True)
    Biskvit_50g151_151_11 = models.CharField(max_length=254, null=True)
    Pryaniki_30g152_152_11 = models.CharField(max_length=254, null=True)
    Pastila_zefir_30g153_153_11 = models.CharField(max_length=254, null=True)
    Vafli_20g154_154_11 = models.CharField(max_length=254, null=True)
    CHipsy_80g155_155_11 = models.CharField(max_length=254, null=True)
    Suhariki_80g156_156_11 = models.CharField(max_length=254, null=True)
    Orehi_30g157_157_11 = models.CharField(max_length=254, null=True)
    Maionez_6g158_158_11 = models.CharField(max_length=254, null=True)
    Ketchup_6g159_159_11 = models.CharField(max_length=254, null=True)
    Soevyi_sous_6g160_160_11 = models.CharField(max_length=254, null=True)
    Soevoe_100ml175_161_11 = models.CharField(max_length=254, null=True)
    Kukuruznoe_100ml176_162_11 = models.CharField(max_length=254, null=True)
    Rastitelnoe_100ml177_163_11 = models.CharField(max_length=254, null=True)
    Podsolnechnoe_100ml178_164_11 = models.CharField(max_length=254, null=True)
    Rapsovoe_100ml179_165_11 = models.CharField(max_length=254, null=True)
    Hlopokovoe_100ml180_166_11 = models.CharField(max_length=254, null=True)
    Olivkovoe_100ml181_167_11 = models.CharField(max_length=254, null=True)
    Slivochnoe_30gr182_168_11 = models.CharField(max_length=254, null=True)
